spring:
  profiles:
    active: local


---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  config:
    activate:
      on-profile:

# 운영 환경
---

server:
  port: 8081
spring:
  config:
    activate:
      on-profile: set1
---

server:
  port: 8082
spring:
  config:
    activate:
      on-profile: set2