spring:
  profiles:
    active: local

---

spring:
  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb