spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL

---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data-h2.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  config:
    activate:
      on-profile:

# 운영 환경
---
spring.profiles.include: real-db

server:
  port: 8081
spring:
  config:
    activate:
      on-profile:
---
spring.profiles.include: real-db

server:
  port: 8082
spring:
  config:
    activate:
      on-profile: